"""migration3

Revision ID: 0e50c813a3d6
Revises: 3979818050dc
Create Date: 2025-11-14 21:26:15.940394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e50c813a3d6'
down_revision = '3979818050dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'color')
    op.drop_column('categories', 'operation_type')
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('categories', sa.Column('operation_type', mysql.ENUM('INCOME', 'EXPENSE'), nullable=False))
    op.add_column('categories', sa.Column('color', mysql.VARCHAR(length=7), nullable=True))
    # ### end Alembic commands ###
