"""migration2

Revision ID: 3979818050dc
Revises: 65202816c828
Create Date: 2025-11-14 13:34:08.495196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3979818050dc'
down_revision = '65202816c828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('operation_type', sa.Enum('INCOME', 'EXPENSE', name='operation_types'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'operation_type')
    # ### end Alembic commands ###
