""" migration3

Revision ID: 045805b230fc
Revises: 527380eb8968
Create Date: 2026-04-01 20:27:42.576018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045805b230fc'
down_revision = '527380eb8968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
